# Generated by Django 5.1.4 on 2025-01-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="user_id",
            field=models.CharField(max_length=4),
        ),
    ]
