# Generated by Django 5.1.4 on 2024-12-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pss", "0004_remove_pssresult_result_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qustionstest",
            name="answer_four",
            field=models.CharField(default="Very Often", max_length=40),
        ),
        migrations.AlterField(
            model_name="qustionstest",
            name="answer_one",
            field=models.CharField(default="Almost Never", max_length=40),
        ),
        migrations.AlterField(
            model_name="qustionstest",
            name="answer_three",
            field=models.CharField(default="Fairly Often", max_length=40),
        ),
        migrations.AlterField(
            model_name="qustionstest",
            name="answer_two",
            field=models.CharField(default="Sometimes", max_length=40),
        ),
        migrations.AlterField(
            model_name="qustionstest",
            name="answer_zero",
            field=models.CharField(default="Never", max_length=40),
        ),
    ]
